# -*- coding: utf-8 -*-
"""Analise_exploratoria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mBcJ_byCEET1visD0tlcbuVtJ27b1mpy
"""

import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('seaborn')

from google.colab import files
arq = files.upload()

df = pd.read_excel("AdventureWorks.xlsx")
df.head()

df.shape

df.dtypes

df["Valor Venda"].sum()

df["Custo"] = df["Custo Unitário"] * df["Quantidade"]

df.head(1)

round(df["Custo"].sum(), 2)

df["Lucro"] = df["Valor Venda"] - df["Custo"]

df.head(1)

round(df["Lucro"].sum(),2)

df["Tempo_envio"] = (df["Data Envio"] - df["Data Venda"]).dt.days
df.head(1)

df.groupby("Marca")["Tempo_envio"].mean()

df.isnull().sum()

#configurando o pandas para resolver notação cientifica de números
pd.options.display.float_format = '{:20,.2f}'.format

df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum()

#resetando index
lucro_ano = df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum().reset_index()
lucro_ano

df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=False)

df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=True).plot.barh(title="Total de produtos vendidos")
plt.xlabel("Total")
plt.ylabel("Produto");

df.groupby(df["Data Venda"].dt.year)["Lucro"].sum().plot.bar(title="Lucro X Ano")
plt.xlabel("Ano")
plt.ylabel("Receita");

df_2009 = df[df["Data Venda"].dt.year == 2009]
df_2009.groupby(df_2009["Data Venda"].dt.month)["Lucro"].sum().plot(title="Lucro X Mes")
plt.xlabel("Mes")
plt.ylabel("Lucro");

df_2009.groupby(df_2009["Marca"])["Lucro"].sum().plot.bar(title="Lucro X Marca")
plt.xlabel("Marca")
plt.ylabel("Lucro");
plt.xticks(rotation='horizontal');

df["Tempo_envio"].describe()

plt.boxplot(df["Tempo_envio"]);

plt.hist(df["Tempo_envio"]);

df["Tempo_envio"].min()

df["Tempo_envio"].max()

df[df["Tempo_envio"]==20]

