-- SELECIONANDO TODOS OS CLIENTES ORDENANDO POR NOME 

SELECT * FROM CLIENTES ORDEM BY NOME ASC

-- SELECIONANDO TODOS OS CLIENTES QUE TIVERAM SERVIÇOS ENTREGUES NOS ULTIMOS 30 DIAS ORDENANDO POR NOME DO PARCEIRO AGRUPANDO PELO TIPO DE SERVIÇO E MOSTRANDO QUAL É SEU VEICULO

SELECT PARC.NOME, PARC.CPF_CNPJ, SRV.DESCRICAO
FROM CLIENTE PARC
INNER JOIN ORDEM_DE_SERVICO PED ON PARC.IDCLIENTE = PED.IDCLIENTE  AND PED.STATUSOS = 'FINALIZADO'
INNER JOIN VEICULO VEI ON VEI.IDVEICULO = PED.IDVEICULO
INNER JOIN CLIENTE_HAS_VEICULO CVEI ON CVEI.IDVEICULO = VEI.IDVEICULO AND CVEI.IDCLIENTE = PARC.IDCLIENTE
INNER JOIN (SELECT SRV.DESCRICAO, SRVOS.NROUNICO FROM SERVICOS SRV INNER JOIN SERVICO_OS SRVOS ON SRV.IDSERVICO = SRVOS.IDSERVICO) SRV ON SRV.NROUNICO = PED.NROUNICO
WHERE PED.DATA_EMISSAO >= PED.DATA_EMISSAO-30
GROUP BY SRV.DESCRICAO HAVING PED.DATA_CONCLUSAO >= PED.DATA_CONCLUSAO-30
ORDER BY PARC.NOMEPARCEIRO ASC


