-- SELECIONANDO TODOS OS PARCEIROS ORDENANDO POR NOME 

SELECT * FROM PARCEIRO ORDEM BY NOME ASC

-- SELECIONANDO TODOS OS PARCEIROS QUE TIVERAM COMPRAS ENTREGUES NOS ULTIMOS 30 DIAS ORDENANDO POR NOME DO PARCEIRO

SELECT PARC.NOMEPARCEIRO, PARC.CPF
FROM PARCEIRO PARC
INNER JOIN PEDIDO_VENDA_COMPRA PED ON PARC.IDPARCEIRO = PED.IDPARCEIRO AND PED.TIPOMOVIMENTO = 'VENDA' AND PED.STATUS = 'ENTREGUE'
WHERE PED.DATAHORA >= PED.DATAHORA-30
ORDER BY PARC.NOMEPARCEIRO ASC

-- AGRUPANDO OS PEDIDOS DE COMPRA E VENDA E TRAZENDO OS TOTAIS DE PRODUTOS E VALORES NOS ULTIMOS 30 DIAS

SELECT PED.TIPOMOVIMENTO, SUM(ITEM.VLRTOTAL) AS 'VLRTOTAL', SUM(ITEM.QUANTIDADE) AS 'QUANTIDADE'
FROM PEDIDO_VENDA_COMPRA PED
INNER JOIN ITENS_PEDIDOS ITEM ON ITEM.IDPEDIDO = PED.IDPEDIDO
GROUP BY PED.TIPOMOVIMENTO HAVING PED.DATAHORA >= PED.DATAHORA-30


--- SELECIONANDO OS ITENS COM ESTOQUE MAIOR QUE ZERO DE FORMA DECRECENTE

SELECT DISTINCT PRO.DESCRICAO, EST.QUANTIDADE 
FROM PRODUTOS PROD
INNER JOIN ESTOQUE EST ON PROD.IDPROD = EST.IDPROD
WHERE EST.QUANTIDAD > 0
ORDER BY EST.QUANTIDADE DESC