-- MySQL Script generated by MySQL Workbench
-- Mon Nov  7 09:40:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Parceiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Parceiro` (
  `idparceiro` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Tipoparceiro` INT NOT NULL,
  `Endereço` VARCHAR(45) NULL,
  `CNPJ_CPF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idparceiro`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `CNPJ_CPF_UNIQUE` ON `Parceiro` (`CNPJ_CPF` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Tipopag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tipopag` (
  `idTipopag` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(45) NULL,
  `Prazo` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipopag`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Descricao_UNIQUE` ON `Tipopag` (`Descricao` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ParcelasTipopag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParcelasTipopag` (
  `idParcelas` INT NOT NULL AUTO_INCREMENT,
  `idTipopag` INT NOT NULL,
  `Parcela` VARCHAR(45) NULL,
  `Percvalor` VARCHAR(45) NULL,
  PRIMARY KEY (`idParcelas`, `idTipopag`),
  CONSTRAINT `fk_ParcelasTipopag_Tipopag`
    FOREIGN KEY (`idTipopag`)
    REFERENCES `Tipopag` (`idTipopag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ParcelasTipopag_Tipopag_idx` ON `ParcelasTipopag` (`idTipopag` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pedidos_venda_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos_venda_compra` (
  `idpedidos` INT NOT NULL AUTO_INCREMENT,
  `idparceiro` INT NOT NULL,
  `idTipopag` INT NOT NULL,
  `statuspedido` VARCHAR(45) NOT NULL,
  `numpedido` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `datahora` DATETIME NOT NULL,
  `tipomovimento` VARCHAR(45) NOT NULL,
  `frete` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpedidos`),
  CONSTRAINT `fk_pedidos_Parceiro1`
    FOREIGN KEY (`idparceiro`)
    REFERENCES `Parceiro` (`idparceiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_Tipopag1`
    FOREIGN KEY (`idTipopag`)
    REFERENCES `Tipopag` (`idTipopag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pedidos_Parceiro1_idx` ON `pedidos_venda_compra` (`idparceiro` ASC) VISIBLE;

CREATE INDEX `fk_pedidos_Tipopag1_idx` ON `pedidos_venda_compra` (`idTipopag` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produtos` (
  `idprodutos` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `impostos` VARCHAR(45) NULL,
  PRIMARY KEY (`idprodutos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque` (
  `idprod` INT NOT NULL AUTO_INCREMENT,
  `controle` VARCHAR(45) NOT NULL,
  `codbarras` VARCHAR(45) NOT NULL,
  `estoque` INT NULL,
  `estoque_max` INT NULL,
  `estoque_min` INT NULL,
  `local` VARCHAR(45) NULL,
  PRIMARY KEY (`idprod`, `controle`, `codbarras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itens_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itens_pedidos` (
  `sequencia` INT NOT NULL AUTO_INCREMENT,
  `idprodutos` INT NOT NULL,
  `idpedidos` INT NOT NULL,
  `controle` VARCHAR(45) NOT NULL,
  `quantidade` INT NULL,
  `vlrunit` DECIMAL(2) NULL,
  `vlrtotal` DECIMAL(2) NULL,
  `qtdpendente` INT NULL,
  `atualizaEstoque` INT NULL,
  PRIMARY KEY (`sequencia`, `idprodutos`, `idpedidos`),
  CONSTRAINT `fk_itens_pedidos_produtos1`
    FOREIGN KEY (`idprodutos`)
    REFERENCES `produtos` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_pedidos_pedidos1`
    FOREIGN KEY (`idpedidos`)
    REFERENCES `pedidos_venda_compra` (`idpedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_pedidos_estoque1`
    FOREIGN KEY (`controle`)
    REFERENCES `estoque` (`controle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_itens_pedidos_produtos1_idx` ON `itens_pedidos` (`idprodutos` ASC) VISIBLE;

CREATE INDEX `fk_itens_pedidos_pedidos1_idx` ON `itens_pedidos` (`idpedidos` ASC) VISIBLE;

CREATE INDEX `fk_itens_pedidos_estoque1_idx` ON `itens_pedidos` (`controle` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `produtos_has_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produtos_has_estoque` (
  `produtos_idprodutos` INT NOT NULL AUTO_INCREMENT,
  `estoque_idprod` INT NOT NULL,
  `estoque_controle` VARCHAR(45) NOT NULL,
  `estoque_codbarras` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`produtos_idprodutos`, `estoque_idprod`, `estoque_controle`, `estoque_codbarras`),
  CONSTRAINT `fk_produtos_has_estoque_produtos1`
    FOREIGN KEY (`produtos_idprodutos`)
    REFERENCES `produtos` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_has_estoque_estoque1`
    FOREIGN KEY (`estoque_idprod` , `estoque_controle` , `estoque_codbarras`)
    REFERENCES `estoque` (`idprod` , `controle` , `codbarras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_produtos_has_estoque_estoque1_idx` ON `produtos_has_estoque` (`estoque_idprod` ASC, `estoque_controle` ASC, `estoque_codbarras` ASC) VISIBLE;

CREATE INDEX `fk_produtos_has_estoque_produtos1_idx` ON `produtos_has_estoque` (`produtos_idprodutos` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Parceiro_has_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Parceiro_has_produtos` (
  `Parceiro_idparceiro` INT NOT NULL,
  `produtos_idprodutos` INT NOT NULL,
  `Quantidade` VARCHAR(45) NULL,
  PRIMARY KEY (`Parceiro_idparceiro`, `produtos_idprodutos`),
  CONSTRAINT `fk_Parceiro_has_produtos_Parceiro1`
    FOREIGN KEY (`Parceiro_idparceiro`)
    REFERENCES `Parceiro` (`idparceiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Parceiro_has_produtos_produtos1`
    FOREIGN KEY (`produtos_idprodutos`)
    REFERENCES `produtos` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Parceiro_has_produtos_produtos1_idx` ON `Parceiro_has_produtos` (`produtos_idprodutos` ASC) VISIBLE;

CREATE INDEX `fk_Parceiro_has_produtos_Parceiro1_idx` ON `Parceiro_has_produtos` (`Parceiro_idparceiro` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Entregas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entregas` (
  `idEntregas` INT NOT NULL AUTO_INCREMENT,
  `idpedidos` INT NOT NULL,
  `StatusEntrega` VARCHAR(45) NULL,
  PRIMARY KEY (`idEntregas`, `idpedidos`),
  CONSTRAINT `fk_Entregas_pedidos_venda_compra1`
    FOREIGN KEY (`idpedidos`)
    REFERENCES `pedidos_venda_compra` (`idpedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Entregas_pedidos_venda_compra1_idx` ON `Entregas` (`idpedidos` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `financeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financeiro` (
  `idfinanceiro` INT NOT NULL AUTO_INCREMENT,
  `idpedidos` INT NOT NULL,
  `receita_despesa` INT NOT NULL,
  `idParcelas` INT NOT NULL,
  `idTipopag` INT NOT NULL,
  `vencimento` DECIMAL(2) NULL,
  `valor` DECIMAL(2) NULL,
  `juros` DECIMAL(2) NULL,
  `desconto` DECIMAL(2) NULL,
  `valorbaixa` DECIMAL(2) NULL,
  `dhbaixa` DATETIME NULL,
  PRIMARY KEY (`idfinanceiro`, `idpedidos`, `idParcelas`, `idTipopag`),
  CONSTRAINT `fk_financeiro_pedidos_venda_compra1`
    FOREIGN KEY (`idpedidos`)
    REFERENCES `pedidos_venda_compra` (`idpedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_financeiro_ParcelasTipopag1`
    FOREIGN KEY (`idParcelas` , `idTipopag`)
    REFERENCES `ParcelasTipopag` (`idParcelas` , `idTipopag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_financeiro_pedidos_venda_compra1_idx` ON `financeiro` (`idpedidos` ASC) VISIBLE;

CREATE INDEX `fk_financeiro_ParcelasTipopag1_idx` ON `financeiro` (`idParcelas` ASC, `idTipopag` ASC) VISIBLE;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
